### ISSUE TITLE
thank u for sharing,any plan for below?

### ISSUE THREAD

**Issue by xeon-ye** [jiangnanboy/Doc-Image-Tool#1]
# DocBlackSpotRemovalItem, #去除不规则黑点
    # DeWatermarkItem, #去水印
    # RemoveStampItem, #去印章
    # HandwritingErasureItem #手写体擦除

**Comment by jiangnanboy** [comment]
Yes, I will continue to complete this app.Do you have any suggestions?

**Comment by xeon-ye** [comment]
great job,maybe some suggestions will be provided for improving.
