### ISSUE TITLE
测试反馈与建议

### ISSUE THREAD

**Issue by xeon-ye** [jiangnanboy/Doc-Image-Tool#2]
1. 漂白对图像质量影响较大，建议优化算法
2. 图像清晰处理会导致程序长时间不响应或挂掉，建议增加独立线程处理优化体验
3. 建议基础功能完备后，可构建Pipeline批量化处理图像
4. 建议融入OCR能力，毕竟图像处理实质都是文本抽取的前置环节

**Comment by jiangnanboy** [comment]
你的建议很好

**Comment by xeon-ye** [comment]
对于印章擦除和印章文字识别有什么学习路径可以探索的，请赐教一二，谢谢

**Comment by gaifanking** [comment]
> 1. 漂白对图像质量影响较大，建议优化算法
> 2. 图像清晰处理会导致程序长时间不响应或挂掉，建议增加独立线程处理优化体验
> 3. 建议基础功能完备后，可构建Pipeline批量化处理图像
> 4. 建议融入OCR能力，毕竟图像处理实质都是文本抽取的前置环节

想向您请教一些图像处理支持，能否加一下我联系方式呢？微信号 YW5qeHVl（Base64后）
